# Do not commit environment files
THMAPSKEY=
THBASEURL=
THENV=sandbox
APOS_S3_BUCKET=
APOS_S3_REGION=
APOS_S3_KEY=
APOS_S3_SECRET=
APOS_ADMIN=
APOS_ADMIN_SECRET=
# prod
APOS_MONGODB_DOMAIN=
APOS_MONGODB_CLUSTER=
APOS_MONGODB_USER=
APOS_MONGODB_SECRET=
